import Link from 'next/link'
import { Card } from '@/components/ui'

export default function HomePage() {
  return (
    <main className="min-h-screen bg-zinc-50 px-6 py-16">
      <section className="mx-auto max-w-5xl">
        <p className="text-sm font-semibold uppercase tracking-widest text-zinc-500">Generated by NEXUS OS</p>
        <h1 className="mt-4 max-w-3xl text-5xl font-black tracking-tight text-zinc-950">Invoice Exception Radar</h1>
        <p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-600">
          A production-grade MVP workspace focused on the three highest-value pain points, with a locked roadmap ready for paid expansion.
        </p>
        <div className="mt-8 flex gap-3">
          <Link href="/dashboard" className="inline-flex rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-700">
            Open dashboard
          </Link>
        </div>
        <div className="mt-12 grid gap-4 md:grid-cols-3">
          <Card className="p-6">
            <h3 className="font-bold text-lg text-zinc-900 tracking-tight mb-2">Top 3 pain-point workflows</h3>
            <p className="text-zinc-600 text-sm">Focus on the most critical tasks that drive business value. Streamlined processes for maximum impact.</p>
          </Card>
          <Card className="p-6">
            <h3 className="font-bold text-lg text-zinc-900 tracking-tight mb-2">Actionable operational insights</h3>
            <p className="text-zinc-600 text-sm">Real-time data and analytics provide clear, concise insights to guide your decisions.</p>
          </Card>
          <Card className="p-6">
            <h3 className="font-bold text-lg text-zinc-900 tracking-tight mb-2">Rapid deployment, zero config</h3>
            <p className="text-zinc-600 text-sm">Get up and running instantly. No complex setup, no hidden costs. Deploy to Vercel in seconds.</p>
          </Card>
        </div>
      </section>
    </main>
  )
}